export const LOADING_JOBS = "LOADING_JOBS";
export const LOADING_SUCCESS_JOBS = "LOADING_SUCCESS_JOBS";
export const LOADING_FAILED_JOBS = "LOADING_FAILED_JOBS";
export const REQUEST_JOBS = "REQUEST_JOBS";
