export const LOADING_PROCESSES = "LOADING_PROCESSES";
export const REQUEST_PROCESSES = "REQUEST_PROCESSES";
export const CREATE_PROCESS = "CREATE_PROCESS";
export const CREATE_REQUEST_PROCESS = "CREATE_REQUEST_PROCESS";
export const DELETE_PROCESS = "DELETE_PROCESS";
export const DELETE_REQUEST_PROCESS = "DELETE_REQUEST_PROCESS";
